name: practice_modulart_architecture
repository: https://github.com/yourusername/practice_modulart_architecture

# 모듈러 아키텍처의 패키지 구조 설정
# packages/**: 모듈 기능들을 담당하는 패키지들
# apps/**: 실제 앱 구현을 담당하는 패키지들
packages:
  - packages/**
  - apps/**

scripts:
  # 코드 분석 명령어: 모든 패키지에서 flutter analyze 실행
  analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages

  # 코드 포맷팅 명령어: 모든 패키지에서 dart format 실행
  format:
    run: melos exec -- "dart format --fix ."
    description: Run `dart format` in all packages

  # 테스트 명령어: 테스트 디렉토리가 있는 모든 패키지에서 테스트 실행
  test:
    run: melos exec -- "flutter test"
    description: Run tests in all packages that have tests
    packageFilters:
      dirExists: test

  # 앱 빌드 명령어: Android와 iOS 빌드 실행
  build:
    run: melos run build:android && melos run build:ios
    description: Build all apps

  # Android 앱 빌드 명령어
  build:android:
    run: |
      melos exec -c 1 --depends-on="flutter" --scope="*app*" -- \
        "flutter build apk --release"
    description: Build Android app

  # iOS 앱 빌드 명령어
  build:ios:
    run: |
      melos exec -c 1 --depends-on="flutter" --scope="*app*" -- \
        "flutter build ios --release --no-codesign"
    description: Build iOS app
