name: practice_modulart_architecture
repository: https://github.com/yourusername/practice_modulart_architecture
packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages

  format:
    run: melos exec -- "dart format --fix ."
    description: Run `dart format` in all packages

  test:
    run: melos exec -- "flutter test"
    description: Run tests in all packages that have tests
    packageFilters:
      dirExists: test

  build:
    run: melos run build:android && melos run build:ios
    description: Build all apps

  build:android:
    run: |
      melos exec -c 1 --depends-on="flutter" --scope="*app*" -- \
        "flutter build apk --release"
    description: Build Android app

  build:ios:
    run: |
      melos exec -c 1 --depends-on="flutter" --scope="*app*" -- \
        "flutter build ios --release --no-codesign"
    description: Build iOS app
