name: router
description: Router module for modular architecture
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 모듈 의존성
  core:
    path: ../core
  auth:
    path: ../features/auth
  home:
    path: ../features/home
  profile:
    path: ../features/profile

  # 라우터 라이브러리
  go_router: ^12.1.1

  # 의존성 주입
  injectable: ^2.3.2
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true
