name: main_app
description: Main Flutter application for modular architecture
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 모듈 의존성
  core:
    path: ../../packages/core
  auth:
    path: ../../packages/features/auth
  home:
    path: ../../packages/features/home
  profile:
    path: ../../packages/features/profile

  # Dependency Injection
  injectable: ^2.3.2
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true
