import 'package:core/di/injector.dart';
import 'package:injectable/injectable.dart';

// This will be generated by the injectable package
// import 'injector.config.dart';

// 자동 생성된 파일 임포트 추가
import 'injector.config.dart';

@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: false,
)
void configureHomeDependencies() {
  // 생성된 init 함수 사용
  init(getIt);
}
